# frozen_string_literal: true

# linux run
# sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
# for ruby 2d: https://www.ruby2d.com/learn/linux/#install-packages
source 'http://rubygems.org'

gem 'debase'
gem 'parser', '< 2.6.2'
gem 'rubocop'
gem 'ruby-debug-ide'
gem 'ruby2d'
gem 'solargraph'
